version: "3.10"

volumes:
  postgres:

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_LOGIN}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
