version: "3.10"

volumes:
  postgres:
  cache:

services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  redis-cache:
    image: redis:alpine
    restart: on-failure
    env_file: .env
    environment:
      - REDIS_DB=${REDIS_NAME}
      - REDIS_USER=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server
    volumes:
      - cache:/data